language: node_js
dist: trusty
node_js: stable
install:
  - npm install hexo-cli -g
  - npm install
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git config --global push.default matching
  - git config --global user.email "${GITHUB_MAIL}"
  - git config --global user.name "${GITHUB_USER}"
  - git reset --mixed origin/master
  - git add --all .
  - git commit -m "Auto Builder of ${GITHUB_USER}'s Blog"
  - git push --quiet --force https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${REPO}.git master

branches:
  only:
    - raw