language: node_js
dist: trusty
node_js: stable
install:
  - npm install hexo-cli -g
  - npm install
script:
  - hexo clean
  - hexo g
  - ls
after_script:
  - cd ./public
  - git init
  - git config --global push.default matching
  - git config --global user.email "imswing@gmail.com"
  - git config --global user.name "devfz"
  - git add --all .
  - git commit -m "Auto Builder of ${GITHUB_USER}'s Blog"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - raw