language: node_js
dist: trusty
node_js: stable
install:
  - npm install hexo-cli -g
  - npm install
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GH_MAIL}"
  - git config --global user.name "${GH_USER}"
  - cd ./themes
  - git submodule init
  - git submodule update
script:
  - cd ..
  - hexo clean
  - hexo g
  - ls
after_script:
  - cd ./public
  - git add --all .
  - git commit -m "Auto Builder of ${GH_USER}'s Blog"
  - git push -f "https://${GH_TOKEN}@${GH_REFS}" master:master
branches:
  only:
    - raw