language: node_js
dist: trusty
node_js: stable
install:
  - npm install hexo-cli -g
  - npm install
script:
  - chmod +X ./deploy.sh
  - hexo clean
  - hexo g
  - bash ./deploy.sh > /dev/null
branches:
  only:
    - raw