language: node_js
dist: trusty
node_js: stable
install:
  - npm install hexo-cli -g
  - npm install
  - git config --global push.default matching
  - git config --global user.email "${GH_MAIL}"
  - git config --global user.name "${GH_USER}"
script:
  - hexo clean
  - hexo g
after_script:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Auto Builder of ${GH_USER}'s Blog"
  - git push --quiet --force https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git master
branches:
  only:
    - raw
